version: "3"
services:
  backend:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./api/.:/usr/src/app 
  frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/.:/usr/src/app 
